###Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [4]:
import numpy as np

## Create array using numpy
## Create a 1D array

arr1=np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1)
print(arr1.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
(6,)


In [13]:
arr2=np.array([1,2,3,4,5])
arr2=arr2.reshape(1,5)   # 1 row and 5 columns
# print(type(arr2))
# print(arr2)
arr2.shape

(1, 5)

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [15]:
# 2D array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [19]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
## Attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [27]:
### Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition
print("Addition:", arr1+arr2)

## Element wise Substraction
print("Substraction:", arr1-arr2)

## Element wise multiplication
print("Multiplication:", arr1*arr2)

## Element wise division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [28]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine 
print(np.sin(arr))

## natural log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
## Array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [52]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [56]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [57]:
## Modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [58]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [60]:
### Statistical concept -- Normalization
## change data to have a mean 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

## calculate mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

## Normalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data:", normalized_data)

print(np.mean(normalized_data))
print(np.std(normalized_data))


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [61]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("Mean:",mean)
#Median
median=np.median(data)
print("Median:",median)
#standard deviation
std_dev=np.std(data)
print("Standard deviation:", std_dev)
#variance
variance=np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [72]:
## Logical Operations
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])